trying: added jpf-core v6

diff --git a/old_projects/jpf-core/bin/ant b/old_projects/jpf-core/bin/ant
--- a/old_projects/jpf-core/bin/ant
+++ b/old_projects/jpf-core/bin/ant
@@ -35,7 +35,8 @@ CP=`find "$JPF_TOOLS" \( -name "*.jar" -or -name "*.zip" \) -exec echo -n {}":" 
 # handle the icky differences of *nix-ish Java installations
 _cygwin=false;
 _darwin=false;
-case "`uname`" in
+UNAME=`uname`
+case $UNAME in
   CYGWIN*) 
     if [ -z "$JAVA_HOME" ]; then
       export JAVA_HOME="$(readlink -f "$(which javac)" 2> /dev/null | sed 's/\/bin\/javac$//' 2> /dev/null)"
@@ -56,21 +57,37 @@ case "`uname`" in
     ;;
            
   Darwin*) 
-    # nothing to do, sun.tools.javac.Main should be in classes.jar
+    if [ -z "$JAVA_HOME" ]; then
+        # that should work on 10.6, 10.7 and 10.8
+       	JAVA_HOME=`/usr/libexec/java_home`
+    fi
+    # JDK 6 uses $JAVA_HOME/../Classes/classes.jar
+    J_HOME=`dirname $JAVA_HOME`
+    JAVAC_JAR=`find $J_HOME -name tools.jar`
+    if [ -z "$JAVAC_JAR" ]; then
+       	JAVAC_JAR=`find $J_HOME -name classes.jar`
+       	if [ -z "$JAVAC_JAR" ]; then
+            echo "no bytecode compiler found: $JAVAC_JAR"
+            exit 1
+        fi
+    fi
+    echo "using javac from ${JAVAC_JAR}"
+    CP="${JAVAC_JAR}:${CP}"    
     ;;
            
   *)
     if [ -z "$JAVA_HOME" ]; then
       export JAVA_HOME="$(readlink -f "$(which javac)" 2> /dev/null | sed 's/\/bin\/javac$//' 2> /dev/null)"
       if [ ! -r "$JAVA_HOME"/lib/tools.jar ]; then
-        echo "JAVA_HOME not set, cannot locate the compiler"
+        echo "JAVA_HOME environment var not set, cannot locate the compiler in: $JAVA_HOME"
         exit 1
       fi
     fi
            
     JAVAC_JAR="$JAVA_HOME/lib/tools.jar"
     if [ ! -f "$JAVAC_JAR" ]; then
-      echo "no bytecode compiler found: $JAVAC_JAR"
+      echo "cannot locate compiler in: $JAVAC_JAR"
+      echo "check your JDK installation and JAVA_HOME environment var: $JAVA_HOME"
       exit 1
     fi
     CP="${JAVAC_JAR}:${CP}"
@@ -78,5 +95,5 @@ case "`uname`" in
 esac
 
 # now run ant with this classpath
-java -classpath "$CP" org.apache.tools.ant.Main "$@"
+java $JVM_FLAGS -classpath "$CP" org.apache.tools.ant.Main "$@"
 
